# Generated by Django 4.2.1 on 2023-05-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0011_delete_post_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='الاسم')),
                ('photo', models.ImageField(blank=True, upload_to='profiles', verbose_name='الصورة')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('text', models.TextField(max_length=50000, verbose_name='النص')),
                ('image', models.ImageField(blank=True, upload_to='posts', verbose_name='الصورة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.profile', verbose_name='الكاتب')),
            ],
        ),
    ]
