# Generated by Django 4.2.1 on 2023-05-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_delete_post_delete_profile'),
        ('posts', '0002_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب'),
        ),
    ]
