# Generated by Django 4.2.1 on 2023-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True, verbose_name='الصورة'),
        ),
    ]
