# Generated by Django 4.2.1 on 2023-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_age_category_alter_borrowing_borrower_and_more'),
        ('posts', '0005_remove_profile_name_post_approved_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book', verbose_name='الكتب التي استعارها'),
        ),
    ]
