# Generated by Django 4.2.1 on 2023-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefield',
            name='file',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
