# Generated by Django 4.2.1 on 2023-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_imagefield_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageField',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='الصورة'),
        ),
    ]
