# Generated by Django 4.2.1 on 2023-05-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_count_book_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='books',
            field=models.ManyToManyField(to='books.book', verbose_name='الكتب التي استعارها'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(verbose_name='تاريخ الاستعارة'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrower', verbose_name='المستعير'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(blank=True, verbose_name='تاريخ الإرجاع'),
        ),
    ]
