# Generated by Django 4.2.1 on 2023-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrower_books_alter_borrowing_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book', verbose_name='الكتب التي استعارها'),
        ),
    ]
