# Generated by Django 4.2.1 on 2023-05-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_borrower_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع'),
        ),
    ]
