# Generated by Django 4.2.1 on 2023-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrowing_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='تم الإرجاع'),
        ),
    ]
