# Generated by Django 4.2.1 on 2023-05-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrowing_returned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('category', 'code')},
        ),
    ]
