# Generated by Django 4.2.1 on 2023-05-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_الرقم_العام_الرقم_الخاص_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='الاسم')),
                ('photo', models.ImageField(blank=True, upload_to='profiles', verbose_name='الصورة')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('text', models.TextField(max_length=50000, verbose_name='النص')),
                ('image', models.ImageField(blank=True, upload_to='posts', verbose_name='الصورة')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.profile', verbose_name='الكاتب')),
            ],
        ),
    ]
