# Generated by Django 4.2.1 on 2023-05-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_profile_alter_book_available_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
