# Generated by Django 4.2.1 on 2023-06-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_age_category_alter_borrowing_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='صورة الكتاب'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='النص')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب')),
            ],
        ),
    ]
