# Generated by Django 4.2.1 on 2023-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_recommendation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.TextField(default='', verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
