# Generated by Django 4.2.1 on 2023-06-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_profile_books'),
        ('books', '0016_recommendation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.profile', verbose_name='المستخدم'),
            preserve_default=False,
        ),
    ]
