# Generated by Django 4.2.1 on 2023-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_recommendation_user_recommendation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الكتاب'),
        ),
    ]
