# Generated by Django 4.2.1 on 2023-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='قبول الاقتراح'),
        ),
    ]
