# Generated by Django 4.2.1 on 2023-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_announcement_remove_recommendation_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.URLField(blank=True, verbose_name='الصورة'),
        ),
    ]
