# Generated by Django 4.2.1 on 2023-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show',
            field=models.BooleanField(default=True, verbose_name='إظهار الإعلان'),
        ),
    ]
