# Generated by Django 4.2.1 on 2023-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_subcategory_remove_book_age_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='الفئة الفرعية',
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.ManyToManyField(to='books.subcategory', verbose_name='الفئة الفرعية'),
        ),
    ]
